import 'package:flutter_chat_ui/flutter_chat_ui.dart';

class MyChatTheme extends ChatTheme {

  MyChatTheme({attachmentButtonIcon,
    backgroundColor,
    dateDividerTextStyle,
    deliveredIcon,
    documentIcon,
    emptyChatPlaceholderTextStyle,
    errorColor,
    errorIcon,
    inputBackgroundColor,
    inputBorderRadius,
    inputTextStyle,
    inputTextColor,
    messageBorderRadius,
    primaryColor,
    receivedMessageBodyTextStyle,
    receivedMessageCaptionTextStyle,
    receivedMessageDocumentIconColor,
    receivedMessageLinkDescriptionTextStyle,
    receivedMessageLinkTitleTextStyle,
    secondaryColor,
    seenIcon,
    sendButtonIcon,
    sentMessageBodyTextStyle,
    sentMessageCaptionTextStyle,
    sentMessageDocumentIconColor,
    sentMessageLinkDescriptionTextStyle,
    sentMessageLinkTitleTextStyle,
    userAvatarNameColors,
    userAvatarTextStyle,
    userNameTextStyle,
    sendingIcon,}) :
        super(
        attachmentButtonIcon: attachmentButtonIcon,
        backgroundColor: backgroundColor,
        dateDividerTextStyle: dateDividerTextStyle,
        deliveredIcon: deliveredIcon,
        documentIcon: documentIcon,
        emptyChatPlaceholderTextStyle: emptyChatPlaceholderTextStyle,
        errorColor: errorColor,
        errorIcon: errorIcon,
        inputBackgroundColor: inputBackgroundColor,
        inputBorderRadius: inputBorderRadius,
        inputTextStyle: inputTextStyle,
        inputTextColor: inputTextColor,
        messageBorderRadius: messageBorderRadius,
        primaryColor: primaryColor,
        receivedMessageBodyTextStyle: receivedMessageBodyTextStyle,
        receivedMessageCaptionTextStyle: receivedMessageCaptionTextStyle,
        receivedMessageDocumentIconColor: receivedMessageDocumentIconColor,
        receivedMessageLinkDescriptionTextStyle: receivedMessageLinkDescriptionTextStyle,
        receivedMessageLinkTitleTextStyle: receivedMessageLinkTitleTextStyle,
        secondaryColor: secondaryColor,
        seenIcon: seenIcon,
        sendButtonIcon: sendButtonIcon,
        sentMessageBodyTextStyle: sentMessageBodyTextStyle,
        sentMessageCaptionTextStyle: sentMessageCaptionTextStyle,
        sentMessageDocumentIconColor: sentMessageDocumentIconColor,
        sentMessageLinkDescriptionTextStyle: sentMessageLinkDescriptionTextStyle,
        sentMessageLinkTitleTextStyle: sentMessageLinkTitleTextStyle,
        userAvatarNameColors: userAvatarNameColors,
        userAvatarTextStyle: userAvatarTextStyle,
        userNameTextStyle: userNameTextStyle,
        sendingIcon: sendingIcon,
      );

}